services:
  smaiax-connector:
    image: smaiax-connector:latest
    container_name: smaiax-connector
    build:
      context: .
      dockerfile: Dockerfile
  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
      - "15672:8080"  # HiveMQ Web UI port
      - "8000:8000"  # HiveMQ WebSocket port
      - "1883:1883"  # MQTT port
    ulimits:
      nofile:
        soft: 500000
        hard: 500000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]  # Simple check for HiveMQ Web UI
      interval: 10s
      timeout: 5s
      retries: 5